spring:
  application:
    name: audit-service
  profiles:
    active: dev
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      config:
        enabled: false
      discovery:
        enabled: false
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/shenzhen_medical?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&connectTimeout=20000&socketTimeout=20000&autoReconnect=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      register-mbeans: true
      connection-init-sql: SET NAMES utf8mb4
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        generate_statistics: false
        cache:
          use_second_level_cache: false
  data:
    redis:
      host: ${REDIS_HOST:172.20.10.164}
      port: ${REDIS_PORT:6380}
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms
  cache:
    redis:
      time-to-live: 7200000
      use-key-prefix: true
      key-prefix: "demo:cache:"
    type: redis

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        # 暴露所有监控端点
        include: "*"
      # 自定义管理端口（可选，用于生产环境安全）
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    # 启用线程转储
    threaddump:
      enabled: true
    # 启用堆转储
    heapdump:
      enabled: true
    # 启用JVM内存信息
    memory:
      enabled: true
    # 启用环境信息
    env:
      enabled: true
    # 启用配置属性
    configprops:
      enabled: true
    # 启用Bean信息
    beans:
      enabled: true
    # 启用性能指标
    metrics:
      enabled: true
    # 启用Prometheus指标
    prometheus:
      enabled: true
  # 监控服务端口（独立端口）
  server:
    port: 9081
  # JMX监控
  jmx:
    exposure:
      include: "*"
  # 监控指标配置
  metrics:
    system:
      diskspace:
        enabled: true
      processor:
        enabled: true
    jvm:
      enabled: true
    jdbc:
      enabled: true
    hikaricp:
      enabled: true
    redis:
      enabled: true
  # Prometheus指标导出
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN
    com.zaxxer.hikari: WARN
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure: WARN
    org.springframework.boot.autoconfigure.condition: WARN
    org.springframework.context.annotation: WARN
    root: INFO
    com.demo: DEBUG

# OpenAPI/Swagger配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
    docExpansion: none
  packages-to-scan: com.demo.controller
  paths-to-match: /api/**