spring:
  application:
    name: fee-query-service
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/shenzhen_medical?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:app_user}
    password: ${DB_PASSWORD:your_secure_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 30000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      register-mbeans: true
      connection-init-sql: SET NAMES utf8mb4
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        generate_statistics: false
        cache:
          use_second_level_cache: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 10000
  cache:
    redis:
      time-to-live: 7200000
      use-key-prefix: true
      key-prefix: "demo:cache:"
    type: redis

server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${server.port}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  server:
    port: 9081

logging:
  level:
    root: INFO
    com.demo: INFO
    org.springframework.web: WARN
    org.springframework.jdbc.core: WARN
    org.springframework.cache: WARN
    org.hibernate.engine.query.spi.QueryPlanCache: WARN
    org.hibernate.type.descriptor.sql: WARN
    com.zaxxer.hikari: WARN
  file:
    name: /var/log/fee-query-service/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB

# OpenAPI/Swagger配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
    docExpansion: none
  packages-to-scan: com.demo.controller
  paths-to-match: /api/** 