server:
  port: 8761  # 标准Eureka端口

spring:
  application:
    name: discovery-service
  
# Eureka服务器配置
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  # 不向自己注册
    fetchRegistry: false       # 不从自己获取注册表
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false  # 关闭自我保护机制，便于开发测试

# 日志配置
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO 