server:
  port: 8082
  address: 0.0.0.0  # 明确绑定到所有接口

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
            
        - id: fee-query-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/settlements/**, /api/diagnosis-details/**, /api/fee-details/**
          filters:
            - JwtAuthentication
            
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'

# JWT配置
jwt:
  secret: your_jwt_secret_key_should_be_at_least_32_bytes_long
  expiration: 86400000  # 24小时有效期(毫秒)

# 关闭Eureka客户端
eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.demo.filter: DEBUG
    reactor.netty: INFO