server:
  port: 8082
  address: 0.0.0.0  # 明确绑定到所有接口

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: fee-query-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/**

# JWT配置
jwt:
  secret: your-secret-key
  expiration: 86400000  # 24小时有效期(毫秒)

# 关闭Eureka客户端
eureka:
  client:
    enabled: false

# 安全配置，允许settlements接口访问
security:
  ignored-paths:
    - /api/settlements/**  # 如果需要公开访问
    - /api/auth/login  # 登录接口必须公开访问
    - /api/fee-details/**  # 费用明细接口
    - /api/diagnosis-details/**  # 诊断详情接口

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG